fix(gatsby-plugin-offline): Update incorrect casing for runtimeCaching handlers
Current configuration object with camel case handlers returns:

```
ValidationError: child "runtimeCaching" fails because ["runtimeCaching" at position 0 fails because [child "handler" fails because ["handler" must be a Function, "handler" must be one of [cacheFirst, cacheOnly, networkFirst, networkOnly, staleWhileRevalidate]]]]
```