fix: prefix graphql type names with underscore if it starts with number (#10007)
if object or array is under field that starts with number it will cause graphql to fail with:
```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6E0F4D382F504Ac5837DF8B7C8618485_2" does not.
```

to workaround it - prefix type name with `_` if it starts with number

fixes #9950

/cc @phonoman