Import react-helmet by name.
Since the react-helmet is exported with a named export, you need to import it by name.
It causes the Element type error.
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `SEO`.
```