fix(query-extraction): handle duplicated graphql query names error (#12931)
## Description

Previously, when there were duplicated graphql query operation names ( i.e `query SiteTitleQuery { site { ... } }`), gatsby threw an error and carried on:

```
success update schema — 0.015 s
error GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- SiteTitleQuery
success extract queries from components — 0.075 s
```

In the latest release (after [this commit?](https://github.com/gatsbyjs/gatsby/commit/91086d43e9b69ba357f7f7ad6bbf2eb0b8b5fbff)), it'll throw an unhandled exception:

```
success update schema — 0.015 s
error UNHANDLED REJECTION
  TypeError: expected a string
  
  - index.js:12 normalizePath
    [gatsby-test]/[normalize-path]/index.js:12:11
  
  - components.js:99 module.exports
    [gatsby-test]/[gatsby]/dist/redux/reducers/components.js:99:40
  
  - redux.js:451 combination
    [gatsby-test]/[redux]/lib/redux.js:451:29
  
  - redux.js:211 dispatch
    [gatsby-test]/[redux]/lib/redux.js:211:22
  
  - index.js:78 action
    [gatsby-test]/[gatsby]/dist/redux/index.js:78:91
  
  - redux.js:468 Object.queryExtractionGraphQLError
    [gatsby-test]/[redux]/lib/redux.js:468:12
```

This pull request modifies `redux/reducers/components.js` so that `state` is returned for `QUERY_EXTRACTION_GRAPHQL_ERROR` & `QUERY_EXTRACTION_BABEL_ERROR` so the error can be seen on the console again.

## Step to reproduce

Just have duplicate query operation name in a site.