Remove unused const config from example
When I pasted the example `src/pages/about/jsx` from https://www.gatsbyjs.org/docs/building-with-components/#page-components into a newly generated "my-gatsby-site" and tried to view the new page at http://localhost:8000/about, I was met with an error:

TypeError: Cannot read property 'site' of undefined

Removing the `const config = this.props.data.site.siteMetadata;` line seems to fix it.  The `config` variable isn't used in the example.