fix(gatsby-plugin-mdx): mkdirp needs to be listed as a direct dependency (#33632)
The `gatsby-node.js` script of `gatsby-plugin-mdx` imports `mkdirp`,
thus it needs to be listed as a dependency to prevent this error with yarn2

```
Error: gatsby-plugin-mdx tried to access mkdirp (a peer dependency)
but it isn't provided by your application; this makes the require call
ambiguous and unsound.
```