FIX: failing build (null fields)
In dev mode I got this error: 
```
TypeError: Cannot read property 'frontmatter' of null
5:06:27 PM:   
5:06:27 PM:   - gatsby-node.js:108 postList.forEach
5:06:27 PM:     /opt/build/repo/gatsby-node.js:108:37
5:06:27 PM:   
5:06:27 PM:   - Array.forEach
5:06:27 PM:   
5:06:27 PM:   - gatsby-node.js:103 Object.exports.createPages
5:06:27 PM:     /opt/build/repo/gatsby-node.js:103:12

```

Because when I had other files that were not .mdx in the "blog" folder, fields are `null`, so build failed. I just `.filter` before actually creating the pages, checking for non-null fields.