fix(gatsby): bump `webpack-virtual-modules`
to get this bug fix: https://github.com/sysgears/webpack-virtual-modules/pull/172

causing this, unclear when:
```
TypeError: Cannot read properties of null (reading 'fileWatchers')
```