Do not hash the chunk name if it is null
When running `gatsby build` I encounter the error:

```
TypeError: Data must be a string or a buffer

  - get-hash-fn.js:16
    [gastby-library]/[gatsby]/dist/utils/get-hash-fn.js:16:10
```

With some debugging I discovered that the chunk name was `null`, so adding this additional check allowed the build to continue.