Feed plugin sanitation
I couln't make the feed plugin work until I finally understood the reason. I had an object in ```siteMetadata``` instead of a string or a number.

It was failing with this error:
```
error Plugin gatsby-plugin-feed returned an error


  TypeError: Cannot convert object to primitive value
  
  - xml.js:177 resolve
    [gatsby-starter-location-github]/[xml]/lib/xml.js:177:34
  
  - xml.js:191 
    [gatsby-starter-location-github]/[xml]/lib/xml.js:191:42
  
  - Array.forEach
  
  - xml.js:184 resolve
    [gatsby-starter-location-github]/[xml]/lib/xml.js:184:24
  
  - xml.js:191 
    [gatsby-starter-location-github]/[xml]/lib/xml.js:191:42
  
  - Array.forEach
  
  - xml.js:184 resolve
    [gatsby-starter-location-github]/[xml]/lib/xml.js:184:24
  
  - xml.js:47 add
    [gatsby-starter-location-github]/[xml]/lib/xml.js:47:24
  
  - xml.js:89 xml
    [gatsby-starter-location-github]/[xml]/lib/xml.js:89:9
  
  - index.js:185 RSS.xml
    [gatsby-starter-location-github]/[rss]/lib/index.js:185:13
  
  - gatsby-node.js:151 _loop$
    [gatsby-starter-location-github]/[gatsby-plugin-feed]/gatsby-node.js:151    :73
```  

All I had to do to fix it was to remove that object from my feed query configuration and thought maybe this could help someone else. The patch simply removes any value under ```siteMetadata``` that isn't a string or a number, and also converts numbers to strings (for use in the rss feed).

Feel free to merge or not. If not, maybe we could add a bit of documentation about that.