Update index.mdx
The  git remote add origin https://github.com/YOUR_GITHUB_USERNAME/YOUR_GITHUB_REPO_NAME.git step in the tutorial is causing an error due that origin can not be added while the git is in the detached state:

error: refname refs/heads/master not found fatal: Branch rename failed

The proposed solution suggests first time users to commit initial files first in order to avoid the error message from detached state.