fix(babel-preset-gatsby): Show a helpful error when used in the wrong environment
This replaces this puzzling error:

Error:  { Error: [BABEL] /home/circleci/project/dangerfile.js: Cannot find module '/home/circleci/project/.cache/babelState.json' (While processing: "/home/circleci/project/node_modules/babel-preset-gatsby/index.js")
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function._module2.default._load (/home/circleci/project/node_modules/override-require/dist/overrideRequire.js:43:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadCachedConfig (/home/circleci/project/node_modules/babel-preset-gatsby/index.js:11:25)
    at preset (/home/circleci/project/node_modules/babel-preset-gatsby/index.js:20:29)
    at loadDescriptor (/home/circleci/project/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction (/home/circleci/project/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPresetDescriptor (/home/circleci/project/node_modules/@babel/core/lib/config/full.js:235:63) code: 'MODULE_NOT_FOUND' }